name: Build Container image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tback/toolbox:latest
